# GitHub provider
provider = "github"
client_id = "Ov23li6iL2s4zimMgUQc"
client_secret = "d2cb4aa42e870470e5d8a32d6707a86e6dce9a3f"

# Cookie
cookie_secret = "6fOQzERXJvnRAl5tXIGBKmZ9uHqpkkibjP_x16hgvl0="   # from: python3 -c "import secrets; print(secrets.token_hex(32))"
cookie_secure = false        # ⚠️ Must be false when using plain IP (no HTTPS)
cookie_domains = ["http://152.69.188.93/"]
cookie_name = "_oauth2_proxy"


upstreams = ["http://127.0.0.1:80"]
http_address = "0.0.0.0:4180"
redirect_url = "http://152.69.188.93:4180:80/oauth2/callback"   # http not https

email_domains = ["*"]
set_xauthrequest = true
reverse_proxy = true
# Option B: Restrict to a GitHub org
# github_org = "your-github-org"

# Option C: Restrict to a specific team within an org
# github_org = "your-github-org"
# github_team = "your-team-slug"

# Option D: Allowlist specific GitHub usernames
github_users = ["thethomasam"]

# Recommended extras
pass_access_token = true
set_xauthrequest = true
reverse_proxy = true